/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as SignupIndexImport } from './routes/signup/index'
import { Route as SignupJammerImport } from './routes/signup/jammer'
import { Route as SignupClientImport } from './routes/signup/client'
import { Route as AuthOauthCallbackImport } from './routes/_auth/oauth-callback'
import { Route as AuthSimpleLayoutImport } from './routes/_auth/_simple-layout'
import { Route as AuthOnboardingImport } from './routes/_auth/_onboarding'
import { Route as AuthAppLayoutImport } from './routes/_auth/_app-layout'
import { Route as AuthAppLayoutSuperAdminImport } from './routes/_auth/_app-layout/_super-admin'
import { Route as AuthOnboardingOnboardingIndexImport } from './routes/_auth/_onboarding/onboarding/index'
import { Route as AuthAppLayoutdashboardIndexImport } from './routes/_auth/_app-layout/(dashboard)/index'
import { Route as AuthSimpleLayoutProjectCreateImport } from './routes/_auth/_simple-layout/project/create'
import { Route as AuthOnboardingOnboardingJammerImport } from './routes/_auth/_onboarding/onboarding/jammer'
import { Route as AuthAppLayoutSuperAdminPaymentTransactionsImport } from './routes/_auth/_app-layout/_super-admin/payment-transactions'
import { Route as AuthAppLayoutProjectIdIndexImport } from './routes/_auth/_app-layout/project/$id/index'
import { Route as AuthSimpleLayoutProjectIdUpsellPaymentCompleteImport } from './routes/_auth/_simple-layout/project/$id/upsell-payment-complete'
import { Route as AuthSimpleLayoutProjectIdUpsellConfirmImport } from './routes/_auth/_simple-layout/project/$id/upsell-confirm'
import { Route as AuthSimpleLayoutProjectIdPaymentCompleteImport } from './routes/_auth/_simple-layout/project/$id/payment-complete'
import { Route as AuthSimpleLayoutProjectIdJammerSelectionImport } from './routes/_auth/_simple-layout/project/$id/jammer-selection'
import { Route as AuthSimpleLayoutProjectIdEditImport } from './routes/_auth/_simple-layout/project/$id/edit'
import { Route as AuthAppLayoutProjectIdStatusImport } from './routes/_auth/_app-layout/project/$id/status'
import { Route as AuthAppLayoutProjectIdRespondImport } from './routes/_auth/_app-layout/project/$id/respond'
import { Route as AuthAppLayoutProjectDraftIdIndexImport } from './routes/_auth/_app-layout/project/draft/$id/index'
import { Route as AuthSimpleLayoutProjectDraftIdEditImport } from './routes/_auth/_simple-layout/project/draft/$id/edit'
import { Route as AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdImport } from './routes/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId'
import { Route as AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdImport } from './routes/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId'
import { Route as AuthAppLayoutProjectIdResponseJammerImport } from './routes/_auth/_app-layout/project/$id/response/$jammer'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const SignupJammerRoute = SignupJammerImport.update({
  path: '/signup/jammer',
  getParentRoute: () => rootRoute,
} as any)

const SignupClientRoute = SignupClientImport.update({
  path: '/signup/client',
  getParentRoute: () => rootRoute,
} as any)

const AuthOauthCallbackRoute = AuthOauthCallbackImport.update({
  path: '/oauth-callback',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSimpleLayoutRoute = AuthSimpleLayoutImport.update({
  id: '/_simple-layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthOnboardingRoute = AuthOnboardingImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAppLayoutRoute = AuthAppLayoutImport.update({
  id: '/_app-layout',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAppLayoutSuperAdminRoute = AuthAppLayoutSuperAdminImport.update({
  id: '/_super-admin',
  getParentRoute: () => AuthAppLayoutRoute,
} as any)

const AuthOnboardingOnboardingIndexRoute =
  AuthOnboardingOnboardingIndexImport.update({
    path: '/onboarding/',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)

const AuthAppLayoutdashboardIndexRoute =
  AuthAppLayoutdashboardIndexImport.update({
    path: '/',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectCreateRoute =
  AuthSimpleLayoutProjectCreateImport.update({
    path: '/project/create',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthOnboardingOnboardingJammerRoute =
  AuthOnboardingOnboardingJammerImport.update({
    path: '/onboarding/jammer',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)

const AuthAppLayoutSuperAdminPaymentTransactionsRoute =
  AuthAppLayoutSuperAdminPaymentTransactionsImport.update({
    path: '/payment-transactions',
    getParentRoute: () => AuthAppLayoutSuperAdminRoute,
  } as any)

const AuthAppLayoutProjectIdIndexRoute =
  AuthAppLayoutProjectIdIndexImport.update({
    path: '/project/$id/',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute =
  AuthSimpleLayoutProjectIdUpsellPaymentCompleteImport.update({
    path: '/project/$id/upsell-payment-complete',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdUpsellConfirmRoute =
  AuthSimpleLayoutProjectIdUpsellConfirmImport.update({
    path: '/project/$id/upsell-confirm',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdPaymentCompleteRoute =
  AuthSimpleLayoutProjectIdPaymentCompleteImport.update({
    path: '/project/$id/payment-complete',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdJammerSelectionRoute =
  AuthSimpleLayoutProjectIdJammerSelectionImport.update({
    path: '/project/$id/jammer-selection',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdEditRoute =
  AuthSimpleLayoutProjectIdEditImport.update({
    path: '/project/$id/edit',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthAppLayoutProjectIdStatusRoute =
  AuthAppLayoutProjectIdStatusImport.update({
    path: '/project/$id/status',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)

const AuthAppLayoutProjectIdRespondRoute =
  AuthAppLayoutProjectIdRespondImport.update({
    path: '/project/$id/respond',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)

const AuthAppLayoutProjectDraftIdIndexRoute =
  AuthAppLayoutProjectDraftIdIndexImport.update({
    path: '/project/draft/$id/',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectDraftIdEditRoute =
  AuthSimpleLayoutProjectDraftIdEditImport.update({
    path: '/project/draft/$id/edit',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute =
  AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdImport.update({
    path: '/project/$id/upsell-checkout/$checkoutId',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute =
  AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdImport.update({
    path: '/project/$id/brief-checkout/$checkoutId',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)

const AuthAppLayoutProjectIdResponseJammerRoute =
  AuthAppLayoutProjectIdResponseJammerImport.update({
    path: '/project/$id/response/$jammer',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_app-layout': {
      id: '/_auth/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppLayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_onboarding': {
      id: '/_auth/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthOnboardingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_simple-layout': {
      id: '/_auth/_simple-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthSimpleLayoutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/oauth-callback': {
      id: '/_auth/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackImport
      parentRoute: typeof AuthImport
    }
    '/signup/client': {
      id: '/signup/client'
      path: '/signup/client'
      fullPath: '/signup/client'
      preLoaderRoute: typeof SignupClientImport
      parentRoute: typeof rootRoute
    }
    '/signup/jammer': {
      id: '/signup/jammer'
      path: '/signup/jammer'
      fullPath: '/signup/jammer'
      preLoaderRoute: typeof SignupJammerImport
      parentRoute: typeof rootRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_app-layout/_super-admin': {
      id: '/_auth/_app-layout/_super-admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppLayoutSuperAdminImport
      parentRoute: typeof AuthAppLayoutImport
    }
    '/_auth/_app-layout/_super-admin/payment-transactions': {
      id: '/_auth/_app-layout/_super-admin/payment-transactions'
      path: '/payment-transactions'
      fullPath: '/payment-transactions'
      preLoaderRoute: typeof AuthAppLayoutSuperAdminPaymentTransactionsImport
      parentRoute: typeof AuthAppLayoutSuperAdminImport
    }
    '/_auth/_onboarding/onboarding/jammer': {
      id: '/_auth/_onboarding/onboarding/jammer'
      path: '/onboarding/jammer'
      fullPath: '/onboarding/jammer'
      preLoaderRoute: typeof AuthOnboardingOnboardingJammerImport
      parentRoute: typeof AuthOnboardingImport
    }
    '/_auth/_simple-layout/project/create': {
      id: '/_auth/_simple-layout/project/create'
      path: '/project/create'
      fullPath: '/project/create'
      preLoaderRoute: typeof AuthSimpleLayoutProjectCreateImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_app-layout/(dashboard)/': {
      id: '/_auth/_app-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthAppLayoutdashboardIndexImport
      parentRoute: typeof AuthAppLayoutImport
    }
    '/_auth/_onboarding/onboarding/': {
      id: '/_auth/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingOnboardingIndexImport
      parentRoute: typeof AuthOnboardingImport
    }
    '/_auth/_app-layout/project/$id/respond': {
      id: '/_auth/_app-layout/project/$id/respond'
      path: '/project/$id/respond'
      fullPath: '/project/$id/respond'
      preLoaderRoute: typeof AuthAppLayoutProjectIdRespondImport
      parentRoute: typeof AuthAppLayoutImport
    }
    '/_auth/_app-layout/project/$id/status': {
      id: '/_auth/_app-layout/project/$id/status'
      path: '/project/$id/status'
      fullPath: '/project/$id/status'
      preLoaderRoute: typeof AuthAppLayoutProjectIdStatusImport
      parentRoute: typeof AuthAppLayoutImport
    }
    '/_auth/_simple-layout/project/$id/edit': {
      id: '/_auth/_simple-layout/project/$id/edit'
      path: '/project/$id/edit'
      fullPath: '/project/$id/edit'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdEditImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_simple-layout/project/$id/jammer-selection': {
      id: '/_auth/_simple-layout/project/$id/jammer-selection'
      path: '/project/$id/jammer-selection'
      fullPath: '/project/$id/jammer-selection'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdJammerSelectionImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_simple-layout/project/$id/payment-complete': {
      id: '/_auth/_simple-layout/project/$id/payment-complete'
      path: '/project/$id/payment-complete'
      fullPath: '/project/$id/payment-complete'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdPaymentCompleteImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_simple-layout/project/$id/upsell-confirm': {
      id: '/_auth/_simple-layout/project/$id/upsell-confirm'
      path: '/project/$id/upsell-confirm'
      fullPath: '/project/$id/upsell-confirm'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdUpsellConfirmImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_simple-layout/project/$id/upsell-payment-complete': {
      id: '/_auth/_simple-layout/project/$id/upsell-payment-complete'
      path: '/project/$id/upsell-payment-complete'
      fullPath: '/project/$id/upsell-payment-complete'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdUpsellPaymentCompleteImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_app-layout/project/$id/': {
      id: '/_auth/_app-layout/project/$id/'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AuthAppLayoutProjectIdIndexImport
      parentRoute: typeof AuthAppLayoutImport
    }
    '/_auth/_app-layout/project/$id/response/$jammer': {
      id: '/_auth/_app-layout/project/$id/response/$jammer'
      path: '/project/$id/response/$jammer'
      fullPath: '/project/$id/response/$jammer'
      preLoaderRoute: typeof AuthAppLayoutProjectIdResponseJammerImport
      parentRoute: typeof AuthAppLayoutImport
    }
    '/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId': {
      id: '/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId'
      path: '/project/$id/brief-checkout/$checkoutId'
      fullPath: '/project/$id/brief-checkout/$checkoutId'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId': {
      id: '/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId'
      path: '/project/$id/upsell-checkout/$checkoutId'
      fullPath: '/project/$id/upsell-checkout/$checkoutId'
      preLoaderRoute: typeof AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_simple-layout/project/draft/$id/edit': {
      id: '/_auth/_simple-layout/project/draft/$id/edit'
      path: '/project/draft/$id/edit'
      fullPath: '/project/draft/$id/edit'
      preLoaderRoute: typeof AuthSimpleLayoutProjectDraftIdEditImport
      parentRoute: typeof AuthSimpleLayoutImport
    }
    '/_auth/_app-layout/project/draft/$id/': {
      id: '/_auth/_app-layout/project/draft/$id/'
      path: '/project/draft/$id'
      fullPath: '/project/draft/$id'
      preLoaderRoute: typeof AuthAppLayoutProjectDraftIdIndexImport
      parentRoute: typeof AuthAppLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthAppLayoutSuperAdminRouteChildren {
  AuthAppLayoutSuperAdminPaymentTransactionsRoute: typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
}

const AuthAppLayoutSuperAdminRouteChildren: AuthAppLayoutSuperAdminRouteChildren =
  {
    AuthAppLayoutSuperAdminPaymentTransactionsRoute:
      AuthAppLayoutSuperAdminPaymentTransactionsRoute,
  }

const AuthAppLayoutSuperAdminRouteWithChildren =
  AuthAppLayoutSuperAdminRoute._addFileChildren(
    AuthAppLayoutSuperAdminRouteChildren,
  )

interface AuthAppLayoutRouteChildren {
  AuthAppLayoutSuperAdminRoute: typeof AuthAppLayoutSuperAdminRouteWithChildren
  AuthAppLayoutdashboardIndexRoute: typeof AuthAppLayoutdashboardIndexRoute
  AuthAppLayoutProjectIdRespondRoute: typeof AuthAppLayoutProjectIdRespondRoute
  AuthAppLayoutProjectIdStatusRoute: typeof AuthAppLayoutProjectIdStatusRoute
  AuthAppLayoutProjectIdIndexRoute: typeof AuthAppLayoutProjectIdIndexRoute
  AuthAppLayoutProjectIdResponseJammerRoute: typeof AuthAppLayoutProjectIdResponseJammerRoute
  AuthAppLayoutProjectDraftIdIndexRoute: typeof AuthAppLayoutProjectDraftIdIndexRoute
}

const AuthAppLayoutRouteChildren: AuthAppLayoutRouteChildren = {
  AuthAppLayoutSuperAdminRoute: AuthAppLayoutSuperAdminRouteWithChildren,
  AuthAppLayoutdashboardIndexRoute: AuthAppLayoutdashboardIndexRoute,
  AuthAppLayoutProjectIdRespondRoute: AuthAppLayoutProjectIdRespondRoute,
  AuthAppLayoutProjectIdStatusRoute: AuthAppLayoutProjectIdStatusRoute,
  AuthAppLayoutProjectIdIndexRoute: AuthAppLayoutProjectIdIndexRoute,
  AuthAppLayoutProjectIdResponseJammerRoute:
    AuthAppLayoutProjectIdResponseJammerRoute,
  AuthAppLayoutProjectDraftIdIndexRoute: AuthAppLayoutProjectDraftIdIndexRoute,
}

const AuthAppLayoutRouteWithChildren = AuthAppLayoutRoute._addFileChildren(
  AuthAppLayoutRouteChildren,
)

interface AuthOnboardingRouteChildren {
  AuthOnboardingOnboardingJammerRoute: typeof AuthOnboardingOnboardingJammerRoute
  AuthOnboardingOnboardingIndexRoute: typeof AuthOnboardingOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingOnboardingJammerRoute: AuthOnboardingOnboardingJammerRoute,
  AuthOnboardingOnboardingIndexRoute: AuthOnboardingOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthSimpleLayoutRouteChildren {
  AuthSimpleLayoutProjectCreateRoute: typeof AuthSimpleLayoutProjectCreateRoute
  AuthSimpleLayoutProjectIdEditRoute: typeof AuthSimpleLayoutProjectIdEditRoute
  AuthSimpleLayoutProjectIdJammerSelectionRoute: typeof AuthSimpleLayoutProjectIdJammerSelectionRoute
  AuthSimpleLayoutProjectIdPaymentCompleteRoute: typeof AuthSimpleLayoutProjectIdPaymentCompleteRoute
  AuthSimpleLayoutProjectIdUpsellConfirmRoute: typeof AuthSimpleLayoutProjectIdUpsellConfirmRoute
  AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute: typeof AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute
  AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute: typeof AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute
  AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute: typeof AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute
  AuthSimpleLayoutProjectDraftIdEditRoute: typeof AuthSimpleLayoutProjectDraftIdEditRoute
}

const AuthSimpleLayoutRouteChildren: AuthSimpleLayoutRouteChildren = {
  AuthSimpleLayoutProjectCreateRoute: AuthSimpleLayoutProjectCreateRoute,
  AuthSimpleLayoutProjectIdEditRoute: AuthSimpleLayoutProjectIdEditRoute,
  AuthSimpleLayoutProjectIdJammerSelectionRoute:
    AuthSimpleLayoutProjectIdJammerSelectionRoute,
  AuthSimpleLayoutProjectIdPaymentCompleteRoute:
    AuthSimpleLayoutProjectIdPaymentCompleteRoute,
  AuthSimpleLayoutProjectIdUpsellConfirmRoute:
    AuthSimpleLayoutProjectIdUpsellConfirmRoute,
  AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute:
    AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute,
  AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute:
    AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute,
  AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute:
    AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute,
  AuthSimpleLayoutProjectDraftIdEditRoute:
    AuthSimpleLayoutProjectDraftIdEditRoute,
}

const AuthSimpleLayoutRouteWithChildren =
  AuthSimpleLayoutRoute._addFileChildren(AuthSimpleLayoutRouteChildren)

interface AuthRouteChildren {
  AuthAppLayoutRoute: typeof AuthAppLayoutRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
  AuthSimpleLayoutRoute: typeof AuthSimpleLayoutRouteWithChildren
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppLayoutRoute: AuthAppLayoutRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
  AuthSimpleLayoutRoute: AuthSimpleLayoutRouteWithChildren,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthAppLayoutSuperAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/jammer': typeof SignupJammerRoute
  '/signup': typeof SignupIndexRoute
  '/payment-transactions': typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  '/onboarding/jammer': typeof AuthOnboardingOnboardingJammerRoute
  '/project/create': typeof AuthSimpleLayoutProjectCreateRoute
  '/': typeof AuthAppLayoutdashboardIndexRoute
  '/onboarding': typeof AuthOnboardingOnboardingIndexRoute
  '/project/$id/respond': typeof AuthAppLayoutProjectIdRespondRoute
  '/project/$id/status': typeof AuthAppLayoutProjectIdStatusRoute
  '/project/$id/edit': typeof AuthSimpleLayoutProjectIdEditRoute
  '/project/$id/jammer-selection': typeof AuthSimpleLayoutProjectIdJammerSelectionRoute
  '/project/$id/payment-complete': typeof AuthSimpleLayoutProjectIdPaymentCompleteRoute
  '/project/$id/upsell-confirm': typeof AuthSimpleLayoutProjectIdUpsellConfirmRoute
  '/project/$id/upsell-payment-complete': typeof AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute
  '/project/$id': typeof AuthAppLayoutProjectIdIndexRoute
  '/project/$id/response/$jammer': typeof AuthAppLayoutProjectIdResponseJammerRoute
  '/project/$id/brief-checkout/$checkoutId': typeof AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute
  '/project/$id/upsell-checkout/$checkoutId': typeof AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute
  '/project/draft/$id/edit': typeof AuthSimpleLayoutProjectDraftIdEditRoute
  '/project/draft/$id': typeof AuthAppLayoutProjectDraftIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthAppLayoutSuperAdminRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/jammer': typeof SignupJammerRoute
  '/signup': typeof SignupIndexRoute
  '/payment-transactions': typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  '/onboarding/jammer': typeof AuthOnboardingOnboardingJammerRoute
  '/project/create': typeof AuthSimpleLayoutProjectCreateRoute
  '/': typeof AuthAppLayoutdashboardIndexRoute
  '/onboarding': typeof AuthOnboardingOnboardingIndexRoute
  '/project/$id/respond': typeof AuthAppLayoutProjectIdRespondRoute
  '/project/$id/status': typeof AuthAppLayoutProjectIdStatusRoute
  '/project/$id/edit': typeof AuthSimpleLayoutProjectIdEditRoute
  '/project/$id/jammer-selection': typeof AuthSimpleLayoutProjectIdJammerSelectionRoute
  '/project/$id/payment-complete': typeof AuthSimpleLayoutProjectIdPaymentCompleteRoute
  '/project/$id/upsell-confirm': typeof AuthSimpleLayoutProjectIdUpsellConfirmRoute
  '/project/$id/upsell-payment-complete': typeof AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute
  '/project/$id': typeof AuthAppLayoutProjectIdIndexRoute
  '/project/$id/response/$jammer': typeof AuthAppLayoutProjectIdResponseJammerRoute
  '/project/$id/brief-checkout/$checkoutId': typeof AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute
  '/project/$id/upsell-checkout/$checkoutId': typeof AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute
  '/project/draft/$id/edit': typeof AuthSimpleLayoutProjectDraftIdEditRoute
  '/project/draft/$id': typeof AuthAppLayoutProjectDraftIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_app-layout': typeof AuthAppLayoutRouteWithChildren
  '/_auth/_onboarding': typeof AuthOnboardingRouteWithChildren
  '/_auth/_simple-layout': typeof AuthSimpleLayoutRouteWithChildren
  '/_auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/jammer': typeof SignupJammerRoute
  '/signup/': typeof SignupIndexRoute
  '/_auth/_app-layout/_super-admin': typeof AuthAppLayoutSuperAdminRouteWithChildren
  '/_auth/_app-layout/_super-admin/payment-transactions': typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  '/_auth/_onboarding/onboarding/jammer': typeof AuthOnboardingOnboardingJammerRoute
  '/_auth/_simple-layout/project/create': typeof AuthSimpleLayoutProjectCreateRoute
  '/_auth/_app-layout/': typeof AuthAppLayoutdashboardIndexRoute
  '/_auth/_onboarding/onboarding/': typeof AuthOnboardingOnboardingIndexRoute
  '/_auth/_app-layout/project/$id/respond': typeof AuthAppLayoutProjectIdRespondRoute
  '/_auth/_app-layout/project/$id/status': typeof AuthAppLayoutProjectIdStatusRoute
  '/_auth/_simple-layout/project/$id/edit': typeof AuthSimpleLayoutProjectIdEditRoute
  '/_auth/_simple-layout/project/$id/jammer-selection': typeof AuthSimpleLayoutProjectIdJammerSelectionRoute
  '/_auth/_simple-layout/project/$id/payment-complete': typeof AuthSimpleLayoutProjectIdPaymentCompleteRoute
  '/_auth/_simple-layout/project/$id/upsell-confirm': typeof AuthSimpleLayoutProjectIdUpsellConfirmRoute
  '/_auth/_simple-layout/project/$id/upsell-payment-complete': typeof AuthSimpleLayoutProjectIdUpsellPaymentCompleteRoute
  '/_auth/_app-layout/project/$id/': typeof AuthAppLayoutProjectIdIndexRoute
  '/_auth/_app-layout/project/$id/response/$jammer': typeof AuthAppLayoutProjectIdResponseJammerRoute
  '/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId': typeof AuthSimpleLayoutProjectIdBriefCheckoutCheckoutIdRoute
  '/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId': typeof AuthSimpleLayoutProjectIdUpsellCheckoutCheckoutIdRoute
  '/_auth/_simple-layout/project/draft/$id/edit': typeof AuthSimpleLayoutProjectDraftIdEditRoute
  '/_auth/_app-layout/project/draft/$id/': typeof AuthAppLayoutProjectDraftIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/oauth-callback'
    | '/signup/client'
    | '/signup/jammer'
    | '/signup'
    | '/payment-transactions'
    | '/onboarding/jammer'
    | '/project/create'
    | '/'
    | '/onboarding'
    | '/project/$id/respond'
    | '/project/$id/status'
    | '/project/$id/edit'
    | '/project/$id/jammer-selection'
    | '/project/$id/payment-complete'
    | '/project/$id/upsell-confirm'
    | '/project/$id/upsell-payment-complete'
    | '/project/$id'
    | '/project/$id/response/$jammer'
    | '/project/$id/brief-checkout/$checkoutId'
    | '/project/$id/upsell-checkout/$checkoutId'
    | '/project/draft/$id/edit'
    | '/project/draft/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/oauth-callback'
    | '/signup/client'
    | '/signup/jammer'
    | '/signup'
    | '/payment-transactions'
    | '/onboarding/jammer'
    | '/project/create'
    | '/'
    | '/onboarding'
    | '/project/$id/respond'
    | '/project/$id/status'
    | '/project/$id/edit'
    | '/project/$id/jammer-selection'
    | '/project/$id/payment-complete'
    | '/project/$id/upsell-confirm'
    | '/project/$id/upsell-payment-complete'
    | '/project/$id'
    | '/project/$id/response/$jammer'
    | '/project/$id/brief-checkout/$checkoutId'
    | '/project/$id/upsell-checkout/$checkoutId'
    | '/project/draft/$id/edit'
    | '/project/draft/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/_app-layout'
    | '/_auth/_onboarding'
    | '/_auth/_simple-layout'
    | '/_auth/oauth-callback'
    | '/signup/client'
    | '/signup/jammer'
    | '/signup/'
    | '/_auth/_app-layout/_super-admin'
    | '/_auth/_app-layout/_super-admin/payment-transactions'
    | '/_auth/_onboarding/onboarding/jammer'
    | '/_auth/_simple-layout/project/create'
    | '/_auth/_app-layout/'
    | '/_auth/_onboarding/onboarding/'
    | '/_auth/_app-layout/project/$id/respond'
    | '/_auth/_app-layout/project/$id/status'
    | '/_auth/_simple-layout/project/$id/edit'
    | '/_auth/_simple-layout/project/$id/jammer-selection'
    | '/_auth/_simple-layout/project/$id/payment-complete'
    | '/_auth/_simple-layout/project/$id/upsell-confirm'
    | '/_auth/_simple-layout/project/$id/upsell-payment-complete'
    | '/_auth/_app-layout/project/$id/'
    | '/_auth/_app-layout/project/$id/response/$jammer'
    | '/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId'
    | '/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId'
    | '/_auth/_simple-layout/project/draft/$id/edit'
    | '/_auth/_app-layout/project/draft/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupClientRoute: typeof SignupClientRoute
  SignupJammerRoute: typeof SignupJammerRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupClientRoute: SignupClientRoute,
  SignupJammerRoute: SignupJammerRoute,
  SignupIndexRoute: SignupIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/signup/client",
        "/signup/jammer",
        "/signup/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_app-layout",
        "/_auth/_onboarding",
        "/_auth/_simple-layout",
        "/_auth/oauth-callback"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/_app-layout": {
      "filePath": "_auth/_app-layout.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_app-layout/_super-admin",
        "/_auth/_app-layout/",
        "/_auth/_app-layout/project/$id/respond",
        "/_auth/_app-layout/project/$id/status",
        "/_auth/_app-layout/project/$id/",
        "/_auth/_app-layout/project/$id/response/$jammer",
        "/_auth/_app-layout/project/draft/$id/"
      ]
    },
    "/_auth/_onboarding": {
      "filePath": "_auth/_onboarding.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_onboarding/onboarding/jammer",
        "/_auth/_onboarding/onboarding/"
      ]
    },
    "/_auth/_simple-layout": {
      "filePath": "_auth/_simple-layout.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_simple-layout/project/create",
        "/_auth/_simple-layout/project/$id/edit",
        "/_auth/_simple-layout/project/$id/jammer-selection",
        "/_auth/_simple-layout/project/$id/payment-complete",
        "/_auth/_simple-layout/project/$id/upsell-confirm",
        "/_auth/_simple-layout/project/$id/upsell-payment-complete",
        "/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId",
        "/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId",
        "/_auth/_simple-layout/project/draft/$id/edit"
      ]
    },
    "/_auth/oauth-callback": {
      "filePath": "_auth/oauth-callback.tsx",
      "parent": "/_auth"
    },
    "/signup/client": {
      "filePath": "signup/client.tsx"
    },
    "/signup/jammer": {
      "filePath": "signup/jammer.tsx"
    },
    "/signup/": {
      "filePath": "signup/index.tsx"
    },
    "/_auth/_app-layout/_super-admin": {
      "filePath": "_auth/_app-layout/_super-admin.tsx",
      "parent": "/_auth/_app-layout",
      "children": [
        "/_auth/_app-layout/_super-admin/payment-transactions"
      ]
    },
    "/_auth/_app-layout/_super-admin/payment-transactions": {
      "filePath": "_auth/_app-layout/_super-admin/payment-transactions.tsx",
      "parent": "/_auth/_app-layout/_super-admin"
    },
    "/_auth/_onboarding/onboarding/jammer": {
      "filePath": "_auth/_onboarding/onboarding/jammer.tsx",
      "parent": "/_auth/_onboarding"
    },
    "/_auth/_simple-layout/project/create": {
      "filePath": "_auth/_simple-layout/project/create.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_app-layout/": {
      "filePath": "_auth/_app-layout/(dashboard)/index.tsx",
      "parent": "/_auth/_app-layout"
    },
    "/_auth/_onboarding/onboarding/": {
      "filePath": "_auth/_onboarding/onboarding/index.tsx",
      "parent": "/_auth/_onboarding"
    },
    "/_auth/_app-layout/project/$id/respond": {
      "filePath": "_auth/_app-layout/project/$id/respond.tsx",
      "parent": "/_auth/_app-layout"
    },
    "/_auth/_app-layout/project/$id/status": {
      "filePath": "_auth/_app-layout/project/$id/status.tsx",
      "parent": "/_auth/_app-layout"
    },
    "/_auth/_simple-layout/project/$id/edit": {
      "filePath": "_auth/_simple-layout/project/$id/edit.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_simple-layout/project/$id/jammer-selection": {
      "filePath": "_auth/_simple-layout/project/$id/jammer-selection.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_simple-layout/project/$id/payment-complete": {
      "filePath": "_auth/_simple-layout/project/$id/payment-complete.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_simple-layout/project/$id/upsell-confirm": {
      "filePath": "_auth/_simple-layout/project/$id/upsell-confirm.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_simple-layout/project/$id/upsell-payment-complete": {
      "filePath": "_auth/_simple-layout/project/$id/upsell-payment-complete.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_app-layout/project/$id/": {
      "filePath": "_auth/_app-layout/project/$id/index.tsx",
      "parent": "/_auth/_app-layout"
    },
    "/_auth/_app-layout/project/$id/response/$jammer": {
      "filePath": "_auth/_app-layout/project/$id/response/$jammer.tsx",
      "parent": "/_auth/_app-layout"
    },
    "/_auth/_simple-layout/project/$id/brief-checkout/$checkoutId": {
      "filePath": "_auth/_simple-layout/project/$id/brief-checkout/$checkoutId.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId": {
      "filePath": "_auth/_simple-layout/project/$id/upsell-checkout/$checkoutId.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_simple-layout/project/draft/$id/edit": {
      "filePath": "_auth/_simple-layout/project/draft/$id/edit.tsx",
      "parent": "/_auth/_simple-layout"
    },
    "/_auth/_app-layout/project/draft/$id/": {
      "filePath": "_auth/_app-layout/project/draft/$id/index.tsx",
      "parent": "/_auth/_app-layout"
    }
  }
}
ROUTE_MANIFEST_END */
