/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SignupJammerRouteImport } from './routes/signup/jammer'
import { Route as SignupClientRouteImport } from './routes/signup/client'
import { Route as MarkupSiteRouteImport } from './routes/markup/site'
import { Route as MarkupPdfRouteImport } from './routes/markup/pdf'
import { Route as MarkupImageRouteImport } from './routes/markup/image'
import { Route as MarkupDocIdRouteImport } from './routes/markup/$docId'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthOauthCallbackRouteImport } from './routes/_auth/oauth-callback'
import { Route as AuthSimpleLayoutRouteImport } from './routes/_auth/_simple-layout'
import { Route as AuthOnboardingRouteImport } from './routes/_auth/_onboarding'
import { Route as AuthAppLayoutRouteImport } from './routes/_auth/_app-layout'
import { Route as AuthAppLayoutMarkupRouteImport } from './routes/_auth/_app-layout/markup'
import { Route as AuthAppLayoutJammerWalletRouteImport } from './routes/_auth/_app-layout/jammer-wallet'
import { Route as AuthAppLayoutSuperAdminRouteImport } from './routes/_auth/_app-layout/_super-admin'
import { Route as AuthOnboardingOnboardingIndexRouteImport } from './routes/_auth/_onboarding/onboarding/index'
import { Route as AuthAppLayoutDashboardIndexRouteImport } from './routes/_auth/_app-layout/dashboard/index'
import { Route as AuthSimpleLayoutProjectCreateRouteImport } from './routes/_auth/_simple-layout/project/create'
import { Route as AuthOnboardingOnboardingJammerRouteImport } from './routes/_auth/_onboarding/onboarding/jammer'
import { Route as AuthAppLayoutSuperAdminWithdrawalRequestsRouteImport } from './routes/_auth/_app-layout/_super-admin/withdrawal-requests'
import { Route as AuthAppLayoutSuperAdminPaymentTransactionsRouteImport } from './routes/_auth/_app-layout/_super-admin/payment-transactions'
import { Route as AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRouteImport } from './routes/_auth/_simple-layout/project/[id]/upsell-payment-complete'
import { Route as AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRouteImport } from './routes/_auth/_simple-layout/project/[id]/upsell-confirm'
import { Route as AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRouteImport } from './routes/_auth/_simple-layout/project/[id]/payment-complete'
import { Route as AuthSimpleLayoutProjectChar91idChar93JammerSelectionRouteImport } from './routes/_auth/_simple-layout/project/[id]/jammer-selection'
import { Route as AuthSimpleLayoutProjectChar91idChar93EditRouteImport } from './routes/_auth/_simple-layout/project/[id]/edit'
import { Route as AuthSimpleLayoutProjectDraftIdEditRouteImport } from './routes/_auth/_simple-layout/project/draft/$id/edit'
import { Route as AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRouteImport } from './routes/_auth/_simple-layout/project/[id]/upsell-checkout/$checkoutId'
import { Route as AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRouteImport } from './routes/_auth/_simple-layout/project/[id]/brief-checkout/$checkoutId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupJammerRoute = SignupJammerRouteImport.update({
  id: '/signup/jammer',
  path: '/signup/jammer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupClientRoute = SignupClientRouteImport.update({
  id: '/signup/client',
  path: '/signup/client',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkupSiteRoute = MarkupSiteRouteImport.update({
  id: '/markup/site',
  path: '/markup/site',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkupPdfRoute = MarkupPdfRouteImport.update({
  id: '/markup/pdf',
  path: '/markup/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkupImageRoute = MarkupImageRouteImport.update({
  id: '/markup/image',
  path: '/markup/image',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkupDocIdRoute = MarkupDocIdRouteImport.update({
  id: '/markup/$docId',
  path: '/markup/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSimpleLayoutRoute = AuthSimpleLayoutRouteImport.update({
  id: '/_simple-layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppLayoutRoute = AuthAppLayoutRouteImport.update({
  id: '/_app-layout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppLayoutMarkupRoute = AuthAppLayoutMarkupRouteImport.update({
  id: '/markup',
  path: '/markup',
  getParentRoute: () => AuthAppLayoutRoute,
} as any)
const AuthAppLayoutJammerWalletRoute =
  AuthAppLayoutJammerWalletRouteImport.update({
    id: '/jammer-wallet',
    path: '/jammer-wallet',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)
const AuthAppLayoutSuperAdminRoute = AuthAppLayoutSuperAdminRouteImport.update({
  id: '/_super-admin',
  getParentRoute: () => AuthAppLayoutRoute,
} as any)
const AuthOnboardingOnboardingIndexRoute =
  AuthOnboardingOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)
const AuthAppLayoutDashboardIndexRoute =
  AuthAppLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthAppLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectCreateRoute =
  AuthSimpleLayoutProjectCreateRouteImport.update({
    id: '/project/create',
    path: '/project/create',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthOnboardingOnboardingJammerRoute =
  AuthOnboardingOnboardingJammerRouteImport.update({
    id: '/onboarding/jammer',
    path: '/onboarding/jammer',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)
const AuthAppLayoutSuperAdminWithdrawalRequestsRoute =
  AuthAppLayoutSuperAdminWithdrawalRequestsRouteImport.update({
    id: '/withdrawal-requests',
    path: '/withdrawal-requests',
    getParentRoute: () => AuthAppLayoutSuperAdminRoute,
  } as any)
const AuthAppLayoutSuperAdminPaymentTransactionsRoute =
  AuthAppLayoutSuperAdminPaymentTransactionsRouteImport.update({
    id: '/payment-transactions',
    path: '/payment-transactions',
    getParentRoute: () => AuthAppLayoutSuperAdminRoute,
  } as any)
const AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute =
  AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRouteImport.update({
    id: '/project/[id]/upsell-payment-complete',
    path: '/project/[id]/upsell-payment-complete',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute =
  AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRouteImport.update({
    id: '/project/[id]/upsell-confirm',
    path: '/project/[id]/upsell-confirm',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute =
  AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRouteImport.update({
    id: '/project/[id]/payment-complete',
    path: '/project/[id]/payment-complete',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute =
  AuthSimpleLayoutProjectChar91idChar93JammerSelectionRouteImport.update({
    id: '/project/[id]/jammer-selection',
    path: '/project/[id]/jammer-selection',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectChar91idChar93EditRoute =
  AuthSimpleLayoutProjectChar91idChar93EditRouteImport.update({
    id: '/project/[id]/edit',
    path: '/project/[id]/edit',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectDraftIdEditRoute =
  AuthSimpleLayoutProjectDraftIdEditRouteImport.update({
    id: '/project/draft/$id/edit',
    path: '/project/draft/$id/edit',
    getParentRoute: () => AuthSimpleLayoutRoute,
  } as any)
const AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute =
  AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRouteImport.update(
    {
      id: '/project/[id]/upsell-checkout/$checkoutId',
      path: '/project/[id]/upsell-checkout/$checkoutId',
      getParentRoute: () => AuthSimpleLayoutRoute,
    } as any,
  )
const AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute =
  AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRouteImport.update(
    {
      id: '/project/[id]/brief-checkout/$checkoutId',
      path: '/project/[id]/brief-checkout/$checkoutId',
      getParentRoute: () => AuthSimpleLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/markup/$docId': typeof MarkupDocIdRoute
  '/markup/image': typeof MarkupImageRoute
  '/markup/pdf': typeof MarkupPdfRoute
  '/markup/site': typeof MarkupSiteRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/jammer': typeof SignupJammerRoute
  '/signup': typeof SignupIndexRoute
  '/jammer-wallet': typeof AuthAppLayoutJammerWalletRoute
  '/markup': typeof AuthAppLayoutMarkupRoute
  '/payment-transactions': typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  '/withdrawal-requests': typeof AuthAppLayoutSuperAdminWithdrawalRequestsRoute
  '/onboarding/jammer': typeof AuthOnboardingOnboardingJammerRoute
  '/project/create': typeof AuthSimpleLayoutProjectCreateRoute
  '/dashboard': typeof AuthAppLayoutDashboardIndexRoute
  '/onboarding': typeof AuthOnboardingOnboardingIndexRoute
  '/project/[id]/edit': typeof AuthSimpleLayoutProjectChar91idChar93EditRoute
  '/project/[id]/jammer-selection': typeof AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute
  '/project/[id]/payment-complete': typeof AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute
  '/project/[id]/upsell-confirm': typeof AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute
  '/project/[id]/upsell-payment-complete': typeof AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute
  '/project/[id]/brief-checkout/$checkoutId': typeof AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute
  '/project/[id]/upsell-checkout/$checkoutId': typeof AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute
  '/project/draft/$id/edit': typeof AuthSimpleLayoutProjectDraftIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/oauth-callback': typeof AuthOauthCallbackRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/markup/$docId': typeof MarkupDocIdRoute
  '/markup/image': typeof MarkupImageRoute
  '/markup/pdf': typeof MarkupPdfRoute
  '/markup/site': typeof MarkupSiteRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/jammer': typeof SignupJammerRoute
  '/signup': typeof SignupIndexRoute
  '/jammer-wallet': typeof AuthAppLayoutJammerWalletRoute
  '/markup': typeof AuthAppLayoutMarkupRoute
  '/payment-transactions': typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  '/withdrawal-requests': typeof AuthAppLayoutSuperAdminWithdrawalRequestsRoute
  '/onboarding/jammer': typeof AuthOnboardingOnboardingJammerRoute
  '/project/create': typeof AuthSimpleLayoutProjectCreateRoute
  '/dashboard': typeof AuthAppLayoutDashboardIndexRoute
  '/onboarding': typeof AuthOnboardingOnboardingIndexRoute
  '/project/[id]/edit': typeof AuthSimpleLayoutProjectChar91idChar93EditRoute
  '/project/[id]/jammer-selection': typeof AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute
  '/project/[id]/payment-complete': typeof AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute
  '/project/[id]/upsell-confirm': typeof AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute
  '/project/[id]/upsell-payment-complete': typeof AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute
  '/project/[id]/brief-checkout/$checkoutId': typeof AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute
  '/project/[id]/upsell-checkout/$checkoutId': typeof AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute
  '/project/draft/$id/edit': typeof AuthSimpleLayoutProjectDraftIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/_app-layout': typeof AuthAppLayoutRouteWithChildren
  '/_auth/_onboarding': typeof AuthOnboardingRouteWithChildren
  '/_auth/_simple-layout': typeof AuthSimpleLayoutRouteWithChildren
  '/_auth/oauth-callback': typeof AuthOauthCallbackRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/markup/$docId': typeof MarkupDocIdRoute
  '/markup/image': typeof MarkupImageRoute
  '/markup/pdf': typeof MarkupPdfRoute
  '/markup/site': typeof MarkupSiteRoute
  '/signup/client': typeof SignupClientRoute
  '/signup/jammer': typeof SignupJammerRoute
  '/signup/': typeof SignupIndexRoute
  '/_auth/_app-layout/_super-admin': typeof AuthAppLayoutSuperAdminRouteWithChildren
  '/_auth/_app-layout/jammer-wallet': typeof AuthAppLayoutJammerWalletRoute
  '/_auth/_app-layout/markup': typeof AuthAppLayoutMarkupRoute
  '/_auth/_app-layout/_super-admin/payment-transactions': typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  '/_auth/_app-layout/_super-admin/withdrawal-requests': typeof AuthAppLayoutSuperAdminWithdrawalRequestsRoute
  '/_auth/_onboarding/onboarding/jammer': typeof AuthOnboardingOnboardingJammerRoute
  '/_auth/_simple-layout/project/create': typeof AuthSimpleLayoutProjectCreateRoute
  '/_auth/_app-layout/dashboard/': typeof AuthAppLayoutDashboardIndexRoute
  '/_auth/_onboarding/onboarding/': typeof AuthOnboardingOnboardingIndexRoute
  '/_auth/_simple-layout/project/[id]/edit': typeof AuthSimpleLayoutProjectChar91idChar93EditRoute
  '/_auth/_simple-layout/project/[id]/jammer-selection': typeof AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute
  '/_auth/_simple-layout/project/[id]/payment-complete': typeof AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute
  '/_auth/_simple-layout/project/[id]/upsell-confirm': typeof AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute
  '/_auth/_simple-layout/project/[id]/upsell-payment-complete': typeof AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute
  '/_auth/_simple-layout/project/[id]/brief-checkout/$checkoutId': typeof AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute
  '/_auth/_simple-layout/project/[id]/upsell-checkout/$checkoutId': typeof AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute
  '/_auth/_simple-layout/project/draft/$id/edit': typeof AuthSimpleLayoutProjectDraftIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/oauth-callback'
    | '/reset-password'
    | '/markup/$docId'
    | '/markup/image'
    | '/markup/pdf'
    | '/markup/site'
    | '/signup/client'
    | '/signup/jammer'
    | '/signup'
    | '/jammer-wallet'
    | '/markup'
    | '/payment-transactions'
    | '/withdrawal-requests'
    | '/onboarding/jammer'
    | '/project/create'
    | '/dashboard'
    | '/onboarding'
    | '/project/[id]/edit'
    | '/project/[id]/jammer-selection'
    | '/project/[id]/payment-complete'
    | '/project/[id]/upsell-confirm'
    | '/project/[id]/upsell-payment-complete'
    | '/project/[id]/brief-checkout/$checkoutId'
    | '/project/[id]/upsell-checkout/$checkoutId'
    | '/project/draft/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/oauth-callback'
    | '/reset-password'
    | '/markup/$docId'
    | '/markup/image'
    | '/markup/pdf'
    | '/markup/site'
    | '/signup/client'
    | '/signup/jammer'
    | '/signup'
    | '/jammer-wallet'
    | '/markup'
    | '/payment-transactions'
    | '/withdrawal-requests'
    | '/onboarding/jammer'
    | '/project/create'
    | '/dashboard'
    | '/onboarding'
    | '/project/[id]/edit'
    | '/project/[id]/jammer-selection'
    | '/project/[id]/payment-complete'
    | '/project/[id]/upsell-confirm'
    | '/project/[id]/upsell-payment-complete'
    | '/project/[id]/brief-checkout/$checkoutId'
    | '/project/[id]/upsell-checkout/$checkoutId'
    | '/project/draft/$id/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/_app-layout'
    | '/_auth/_onboarding'
    | '/_auth/_simple-layout'
    | '/_auth/oauth-callback'
    | '/_auth/reset-password'
    | '/markup/$docId'
    | '/markup/image'
    | '/markup/pdf'
    | '/markup/site'
    | '/signup/client'
    | '/signup/jammer'
    | '/signup/'
    | '/_auth/_app-layout/_super-admin'
    | '/_auth/_app-layout/jammer-wallet'
    | '/_auth/_app-layout/markup'
    | '/_auth/_app-layout/_super-admin/payment-transactions'
    | '/_auth/_app-layout/_super-admin/withdrawal-requests'
    | '/_auth/_onboarding/onboarding/jammer'
    | '/_auth/_simple-layout/project/create'
    | '/_auth/_app-layout/dashboard/'
    | '/_auth/_onboarding/onboarding/'
    | '/_auth/_simple-layout/project/[id]/edit'
    | '/_auth/_simple-layout/project/[id]/jammer-selection'
    | '/_auth/_simple-layout/project/[id]/payment-complete'
    | '/_auth/_simple-layout/project/[id]/upsell-confirm'
    | '/_auth/_simple-layout/project/[id]/upsell-payment-complete'
    | '/_auth/_simple-layout/project/[id]/brief-checkout/$checkoutId'
    | '/_auth/_simple-layout/project/[id]/upsell-checkout/$checkoutId'
    | '/_auth/_simple-layout/project/draft/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarkupDocIdRoute: typeof MarkupDocIdRoute
  MarkupImageRoute: typeof MarkupImageRoute
  MarkupPdfRoute: typeof MarkupPdfRoute
  MarkupSiteRoute: typeof MarkupSiteRoute
  SignupClientRoute: typeof SignupClientRoute
  SignupJammerRoute: typeof SignupJammerRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/jammer': {
      id: '/signup/jammer'
      path: '/signup/jammer'
      fullPath: '/signup/jammer'
      preLoaderRoute: typeof SignupJammerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/client': {
      id: '/signup/client'
      path: '/signup/client'
      fullPath: '/signup/client'
      preLoaderRoute: typeof SignupClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markup/site': {
      id: '/markup/site'
      path: '/markup/site'
      fullPath: '/markup/site'
      preLoaderRoute: typeof MarkupSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markup/pdf': {
      id: '/markup/pdf'
      path: '/markup/pdf'
      fullPath: '/markup/pdf'
      preLoaderRoute: typeof MarkupPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markup/image': {
      id: '/markup/image'
      path: '/markup/image'
      fullPath: '/markup/image'
      preLoaderRoute: typeof MarkupImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markup/$docId': {
      id: '/markup/$docId'
      path: '/markup/$docId'
      fullPath: '/markup/$docId'
      preLoaderRoute: typeof MarkupDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/oauth-callback': {
      id: '/_auth/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_simple-layout': {
      id: '/_auth/_simple-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthSimpleLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_onboarding': {
      id: '/_auth/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_app-layout': {
      id: '/_auth/_app-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_app-layout/markup': {
      id: '/_auth/_app-layout/markup'
      path: '/markup'
      fullPath: '/markup'
      preLoaderRoute: typeof AuthAppLayoutMarkupRouteImport
      parentRoute: typeof AuthAppLayoutRoute
    }
    '/_auth/_app-layout/jammer-wallet': {
      id: '/_auth/_app-layout/jammer-wallet'
      path: '/jammer-wallet'
      fullPath: '/jammer-wallet'
      preLoaderRoute: typeof AuthAppLayoutJammerWalletRouteImport
      parentRoute: typeof AuthAppLayoutRoute
    }
    '/_auth/_app-layout/_super-admin': {
      id: '/_auth/_app-layout/_super-admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAppLayoutSuperAdminRouteImport
      parentRoute: typeof AuthAppLayoutRoute
    }
    '/_auth/_onboarding/onboarding/': {
      id: '/_auth/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingOnboardingIndexRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/_app-layout/dashboard/': {
      id: '/_auth/_app-layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthAppLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthAppLayoutRoute
    }
    '/_auth/_simple-layout/project/create': {
      id: '/_auth/_simple-layout/project/create'
      path: '/project/create'
      fullPath: '/project/create'
      preLoaderRoute: typeof AuthSimpleLayoutProjectCreateRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_onboarding/onboarding/jammer': {
      id: '/_auth/_onboarding/onboarding/jammer'
      path: '/onboarding/jammer'
      fullPath: '/onboarding/jammer'
      preLoaderRoute: typeof AuthOnboardingOnboardingJammerRouteImport
      parentRoute: typeof AuthOnboardingRoute
    }
    '/_auth/_app-layout/_super-admin/withdrawal-requests': {
      id: '/_auth/_app-layout/_super-admin/withdrawal-requests'
      path: '/withdrawal-requests'
      fullPath: '/withdrawal-requests'
      preLoaderRoute: typeof AuthAppLayoutSuperAdminWithdrawalRequestsRouteImport
      parentRoute: typeof AuthAppLayoutSuperAdminRoute
    }
    '/_auth/_app-layout/_super-admin/payment-transactions': {
      id: '/_auth/_app-layout/_super-admin/payment-transactions'
      path: '/payment-transactions'
      fullPath: '/payment-transactions'
      preLoaderRoute: typeof AuthAppLayoutSuperAdminPaymentTransactionsRouteImport
      parentRoute: typeof AuthAppLayoutSuperAdminRoute
    }
    '/_auth/_simple-layout/project/[id]/upsell-payment-complete': {
      id: '/_auth/_simple-layout/project/[id]/upsell-payment-complete'
      path: '/project/[id]/upsell-payment-complete'
      fullPath: '/project/[id]/upsell-payment-complete'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/[id]/upsell-confirm': {
      id: '/_auth/_simple-layout/project/[id]/upsell-confirm'
      path: '/project/[id]/upsell-confirm'
      fullPath: '/project/[id]/upsell-confirm'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/[id]/payment-complete': {
      id: '/_auth/_simple-layout/project/[id]/payment-complete'
      path: '/project/[id]/payment-complete'
      fullPath: '/project/[id]/payment-complete'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/[id]/jammer-selection': {
      id: '/_auth/_simple-layout/project/[id]/jammer-selection'
      path: '/project/[id]/jammer-selection'
      fullPath: '/project/[id]/jammer-selection'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93JammerSelectionRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/[id]/edit': {
      id: '/_auth/_simple-layout/project/[id]/edit'
      path: '/project/[id]/edit'
      fullPath: '/project/[id]/edit'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93EditRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/draft/$id/edit': {
      id: '/_auth/_simple-layout/project/draft/$id/edit'
      path: '/project/draft/$id/edit'
      fullPath: '/project/draft/$id/edit'
      preLoaderRoute: typeof AuthSimpleLayoutProjectDraftIdEditRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/[id]/upsell-checkout/$checkoutId': {
      id: '/_auth/_simple-layout/project/[id]/upsell-checkout/$checkoutId'
      path: '/project/[id]/upsell-checkout/$checkoutId'
      fullPath: '/project/[id]/upsell-checkout/$checkoutId'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
    '/_auth/_simple-layout/project/[id]/brief-checkout/$checkoutId': {
      id: '/_auth/_simple-layout/project/[id]/brief-checkout/$checkoutId'
      path: '/project/[id]/brief-checkout/$checkoutId'
      fullPath: '/project/[id]/brief-checkout/$checkoutId'
      preLoaderRoute: typeof AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRouteImport
      parentRoute: typeof AuthSimpleLayoutRoute
    }
  }
}

interface AuthAppLayoutSuperAdminRouteChildren {
  AuthAppLayoutSuperAdminPaymentTransactionsRoute: typeof AuthAppLayoutSuperAdminPaymentTransactionsRoute
  AuthAppLayoutSuperAdminWithdrawalRequestsRoute: typeof AuthAppLayoutSuperAdminWithdrawalRequestsRoute
}

const AuthAppLayoutSuperAdminRouteChildren: AuthAppLayoutSuperAdminRouteChildren =
  {
    AuthAppLayoutSuperAdminPaymentTransactionsRoute:
      AuthAppLayoutSuperAdminPaymentTransactionsRoute,
    AuthAppLayoutSuperAdminWithdrawalRequestsRoute:
      AuthAppLayoutSuperAdminWithdrawalRequestsRoute,
  }

const AuthAppLayoutSuperAdminRouteWithChildren =
  AuthAppLayoutSuperAdminRoute._addFileChildren(
    AuthAppLayoutSuperAdminRouteChildren,
  )

interface AuthAppLayoutRouteChildren {
  AuthAppLayoutSuperAdminRoute: typeof AuthAppLayoutSuperAdminRouteWithChildren
  AuthAppLayoutJammerWalletRoute: typeof AuthAppLayoutJammerWalletRoute
  AuthAppLayoutMarkupRoute: typeof AuthAppLayoutMarkupRoute
  AuthAppLayoutDashboardIndexRoute: typeof AuthAppLayoutDashboardIndexRoute
}

const AuthAppLayoutRouteChildren: AuthAppLayoutRouteChildren = {
  AuthAppLayoutSuperAdminRoute: AuthAppLayoutSuperAdminRouteWithChildren,
  AuthAppLayoutJammerWalletRoute: AuthAppLayoutJammerWalletRoute,
  AuthAppLayoutMarkupRoute: AuthAppLayoutMarkupRoute,
  AuthAppLayoutDashboardIndexRoute: AuthAppLayoutDashboardIndexRoute,
}

const AuthAppLayoutRouteWithChildren = AuthAppLayoutRoute._addFileChildren(
  AuthAppLayoutRouteChildren,
)

interface AuthOnboardingRouteChildren {
  AuthOnboardingOnboardingJammerRoute: typeof AuthOnboardingOnboardingJammerRoute
  AuthOnboardingOnboardingIndexRoute: typeof AuthOnboardingOnboardingIndexRoute
}

const AuthOnboardingRouteChildren: AuthOnboardingRouteChildren = {
  AuthOnboardingOnboardingJammerRoute: AuthOnboardingOnboardingJammerRoute,
  AuthOnboardingOnboardingIndexRoute: AuthOnboardingOnboardingIndexRoute,
}

const AuthOnboardingRouteWithChildren = AuthOnboardingRoute._addFileChildren(
  AuthOnboardingRouteChildren,
)

interface AuthSimpleLayoutRouteChildren {
  AuthSimpleLayoutProjectCreateRoute: typeof AuthSimpleLayoutProjectCreateRoute
  AuthSimpleLayoutProjectChar91idChar93EditRoute: typeof AuthSimpleLayoutProjectChar91idChar93EditRoute
  AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute: typeof AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute
  AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute: typeof AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute
  AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute: typeof AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute
  AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute: typeof AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute
  AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute: typeof AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute
  AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute: typeof AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute
  AuthSimpleLayoutProjectDraftIdEditRoute: typeof AuthSimpleLayoutProjectDraftIdEditRoute
}

const AuthSimpleLayoutRouteChildren: AuthSimpleLayoutRouteChildren = {
  AuthSimpleLayoutProjectCreateRoute: AuthSimpleLayoutProjectCreateRoute,
  AuthSimpleLayoutProjectChar91idChar93EditRoute:
    AuthSimpleLayoutProjectChar91idChar93EditRoute,
  AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute:
    AuthSimpleLayoutProjectChar91idChar93JammerSelectionRoute,
  AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute:
    AuthSimpleLayoutProjectChar91idChar93PaymentCompleteRoute,
  AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute:
    AuthSimpleLayoutProjectChar91idChar93UpsellConfirmRoute,
  AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute:
    AuthSimpleLayoutProjectChar91idChar93UpsellPaymentCompleteRoute,
  AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute:
    AuthSimpleLayoutProjectChar91idChar93BriefCheckoutCheckoutIdRoute,
  AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute:
    AuthSimpleLayoutProjectChar91idChar93UpsellCheckoutCheckoutIdRoute,
  AuthSimpleLayoutProjectDraftIdEditRoute:
    AuthSimpleLayoutProjectDraftIdEditRoute,
}

const AuthSimpleLayoutRouteWithChildren =
  AuthSimpleLayoutRoute._addFileChildren(AuthSimpleLayoutRouteChildren)

interface AuthRouteChildren {
  AuthAppLayoutRoute: typeof AuthAppLayoutRouteWithChildren
  AuthOnboardingRoute: typeof AuthOnboardingRouteWithChildren
  AuthSimpleLayoutRoute: typeof AuthSimpleLayoutRouteWithChildren
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppLayoutRoute: AuthAppLayoutRouteWithChildren,
  AuthOnboardingRoute: AuthOnboardingRouteWithChildren,
  AuthSimpleLayoutRoute: AuthSimpleLayoutRouteWithChildren,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  MarkupDocIdRoute: MarkupDocIdRoute,
  MarkupImageRoute: MarkupImageRoute,
  MarkupPdfRoute: MarkupPdfRoute,
  MarkupSiteRoute: MarkupSiteRoute,
  SignupClientRoute: SignupClientRoute,
  SignupJammerRoute: SignupJammerRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
