/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as SignupIndexImport } from './routes/signup/index'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as SignupJammerImport } from './routes/signup/jammer'
import { Route as SignupClientImport } from './routes/signup/client'
import { Route as AuthOauthCallbackImport } from './routes/_auth/oauth-callback'
import { Route as AuthCreateBriefImport } from './routes/_auth/create-brief'
import { Route as AuthOnboardingImport } from './routes/_auth/_onboarding'
import { Route as AuthOnboardingOnboardingIndexImport } from './routes/_auth/_onboarding/onboarding/index'
import { Route as AuthOnboardingOnboardingJammerImport } from './routes/_auth/_onboarding/onboarding/jammer'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const SignupIndexRoute = SignupIndexImport.update({
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const SignupJammerRoute = SignupJammerImport.update({
  path: '/signup/jammer',
  getParentRoute: () => rootRoute,
} as any)

const SignupClientRoute = SignupClientImport.update({
  path: '/signup/client',
  getParentRoute: () => rootRoute,
} as any)

const AuthOauthCallbackRoute = AuthOauthCallbackImport.update({
  path: '/oauth-callback',
  getParentRoute: () => AuthRoute,
} as any)

const AuthCreateBriefRoute = AuthCreateBriefImport.update({
  path: '/create-brief',
  getParentRoute: () => AuthRoute,
} as any)

const AuthOnboardingRoute = AuthOnboardingImport.update({
  id: '/_onboarding',
  getParentRoute: () => AuthRoute,
} as any)

const AuthOnboardingOnboardingIndexRoute =
  AuthOnboardingOnboardingIndexImport.update({
    path: '/onboarding/',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)

const AuthOnboardingOnboardingJammerRoute =
  AuthOnboardingOnboardingJammerImport.update({
    path: '/onboarding/jammer',
    getParentRoute: () => AuthOnboardingRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_onboarding': {
      id: '/_auth/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthOnboardingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/create-brief': {
      id: '/_auth/create-brief'
      path: '/create-brief'
      fullPath: '/create-brief'
      preLoaderRoute: typeof AuthCreateBriefImport
      parentRoute: typeof AuthImport
    }
    '/_auth/oauth-callback': {
      id: '/_auth/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof AuthOauthCallbackImport
      parentRoute: typeof AuthImport
    }
    '/signup/client': {
      id: '/signup/client'
      path: '/signup/client'
      fullPath: '/signup/client'
      preLoaderRoute: typeof SignupClientImport
      parentRoute: typeof rootRoute
    }
    '/signup/jammer': {
      id: '/signup/jammer'
      path: '/signup/jammer'
      fullPath: '/signup/jammer'
      preLoaderRoute: typeof SignupJammerImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_onboarding/onboarding/jammer': {
      id: '/_auth/_onboarding/onboarding/jammer'
      path: '/onboarding/jammer'
      fullPath: '/onboarding/jammer'
      preLoaderRoute: typeof AuthOnboardingOnboardingJammerImport
      parentRoute: typeof AuthOnboardingImport
    }
    '/_auth/_onboarding/onboarding/': {
      id: '/_auth/_onboarding/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthOnboardingOnboardingIndexImport
      parentRoute: typeof AuthOnboardingImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthOnboardingRoute: AuthOnboardingRoute.addChildren({
      AuthOnboardingOnboardingJammerRoute,
      AuthOnboardingOnboardingIndexRoute,
    }),
    AuthCreateBriefRoute,
    AuthOauthCallbackRoute,
    AuthIndexRoute,
  }),
  LoginRoute,
  SignupClientRoute,
  SignupJammerRoute,
  SignupIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/signup/client",
        "/signup/jammer",
        "/signup/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_onboarding",
        "/_auth/create-brief",
        "/_auth/oauth-callback",
        "/_auth/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/_onboarding": {
      "filePath": "_auth/_onboarding.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_onboarding/onboarding/jammer",
        "/_auth/_onboarding/onboarding/"
      ]
    },
    "/_auth/create-brief": {
      "filePath": "_auth/create-brief.tsx",
      "parent": "/_auth"
    },
    "/_auth/oauth-callback": {
      "filePath": "_auth/oauth-callback.tsx",
      "parent": "/_auth"
    },
    "/signup/client": {
      "filePath": "signup/client.tsx"
    },
    "/signup/jammer": {
      "filePath": "signup/jammer.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/signup/": {
      "filePath": "signup/index.tsx"
    },
    "/_auth/_onboarding/onboarding/jammer": {
      "filePath": "_auth/_onboarding/onboarding/jammer.tsx",
      "parent": "/_auth/_onboarding"
    },
    "/_auth/_onboarding/onboarding/": {
      "filePath": "_auth/_onboarding/onboarding/index.tsx",
      "parent": "/_auth/_onboarding"
    }
  }
}
ROUTE_MANIFEST_END */
